[package]
name = "interest_protocol"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "amnn/devnet+clock-test" }

[addresses]
interest_protocol =  "0x0"
sui =  "0000000000000000000000000000000000000002"
dev= "0xa09888cbd5b3329f86cf945bb3872a31ae835c47"
