[package]
name = "Oracle"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }
SwitchboardStdLib = { git = "https://github.com/switchboard-xyz/sbv2-sui.git", subdir = "move/testnet/switchboard_std/", rev = "main"  }
Library =  { local = "../library" }

[addresses]
oracle = "0x0"
sui =  "0x2"
switchboard_std = "0x98670585b87e06628ef2d7f7cb1e7bee8ada65b43b82997935225a7e6e21d18e"
library =  "bd8d525f659483420b2da568b924c63973240b2ddfd148e3909e17c43d189764"